# Generated by Django 5.2.7 on 2025-12-07 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('description', models.TextField()),
                ('news_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date',
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(verbose_name='Время сеанса'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session'),
        ),
    ]
