# Generated by Django 5.2.7 on 2025-12-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_remove_ticket_date_alter_session_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(upload_to='news/'),
        ),
    ]
