# Generated by Django 5.2.7 on 2025-12-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь'), ('staff', 'Персонал')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='show',
            name='poster',
            field=models.ImageField(upload_to='shows/'),
        ),
    ]
