# Generated by Django 5.2.7 on 2025-12-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_role_alter_actor_photo_alter_show_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='show',
            new_name='session',
        ),
    ]
